import type { ColumnDef, Row } from '../types';

export const columns: ColumnDef[] = [
  { key: 'name', label: 'Название', type: 'text', sortable: true },
  {
    key: 'vertical',
    label: 'Вертикаль',
    type: 'select',
    sortable: true,
    filterable: true,
    badge: true,
    badgeVariant: {
      'AI': 'purple',
      'IT': 'blue',
      'WorkOS': 'teal',
      'Data': 'amber',
    },
  },
  {
    key: 'verdict',
    label: 'Вердикт',
    type: 'select',
    sortable: true,
    filterable: true,
    badge: true,
    order: ['Берём', 'Смотрим', 'Мимо'],
    badgeVariant: { 'Берём': 'green', 'Смотрим': 'amber', 'Мимо': 'grey' },
  },
  { key: 'price', label: 'Цена, $/мес', type: 'number', sortable: true },
  { key: 'link', label: 'Ссылка', type: 'url' },
  // 'text', а не 'long-text': long-text компонент из сетки убирает и показывает
  // только на карточке записи, а карточки в этом демо нет.
  { key: 'note', label: 'Заметка', type: 'text' },
];

export const rows: Row[] = [
  {
    id: '1',
    name: 'Figma',
    vertical: 'IT',
    verdict: 'Берём',
    price: 15,
    link: 'https://figma.com',
    note: 'Дизайн-файлы и прототипы. Уже стоит у команды, отдельного решения не требует.',
  },
  {
    id: '2',
    name: 'Linear',
    vertical: 'WorkOS',
    verdict: 'Берём',
    price: 8,
    link: 'https://linear.app',
    note: 'Трекер задач. Быстрый, с нормальным API — можно повесить автоматизации.',
  },
  {
    id: '3',
    name: 'Notion',
    vertical: 'WorkOS',
    verdict: 'Смотрим',
    price: 10,
    link: 'https://notion.so',
    note: 'База знаний. Пересекается с внутренним исследователем, надо решить, что где живёт.',
  },
  {
    id: '4',
    name: 'Airtable',
    vertical: 'Data',
    verdict: 'Смотрим',
    price: 20,
    link: 'https://airtable.com',
    note: 'Таблицы как база. Ровно та ниша, которую закрывает MindSheet, — сравниваем.',
  },
  {
    id: '5',
    name: 'Retool',
    vertical: 'IT',
    verdict: 'Мимо',
    price: 50,
    link: 'https://retool.com',
    note: 'Внутренние админки. Дорого для нашего объёма, свои экраны пишем руками.',
  },
  {
    id: '6',
    name: 'Anthropic Claude',
    vertical: 'AI',
    verdict: 'Берём',
    price: 20,
    link: 'https://claude.ai',
    note: 'Основная модель. На ней же построены секретарь и исследователь.',
  },
  {
    id: '7',
    name: 'Tavily',
    vertical: 'AI',
    verdict: 'Берём',
    price: 30,
    link: 'https://tavily.com',
    note: 'Поисковый слой для deep-research. Оплата по запросам.',
  },
  {
    id: '8',
    name: 'Supabase',
    vertical: 'Data',
    verdict: 'Берём',
    price: 25,
    link: 'https://supabase.com',
    note: 'Postgres с готовой авторизацией. Хранит базы знаний исследователя.',
  },
  {
    id: '9',
    name: 'Fathom',
    vertical: 'WorkOS',
    verdict: 'Берём',
    price: 19,
    link: 'https://fathom.video',
    note: 'Запись и транскрипты встреч. Отсюда секретарь тянет исходники протоколов.',
  },
  {
    id: '10',
    name: 'Zapier',
    vertical: 'WorkOS',
    verdict: 'Мимо',
    price: 30,
    link: 'https://zapier.com',
    note: 'Связки между сервисами. Наши сценарии проще закрыть скриптом.',
  },
  {
    id: '11',
    name: 'Vercel',
    vertical: 'IT',
    verdict: 'Берём',
    price: 20,
    link: 'https://vercel.com',
    note: 'Хостинг фронтов. Сюда же выложено это самое демо.',
  },
  {
    id: '12',
    name: 'Metabase',
    vertical: 'Data',
    verdict: 'Смотрим',
    price: 0,
    link: 'https://metabase.com',
    note: 'BI поверх Postgres. Self-hosted бесплатно, но нужен свой сервер.',
  },
  {
    id: '13',
    name: 'Perplexity',
    vertical: 'AI',
    verdict: 'Смотрим',
    price: 20,
    link: 'https://perplexity.ai',
    note: 'Поиск с ответами. Частично дублирует связку Claude + Tavily.',
  },
  {
    id: '14',
    name: 'GitHub',
    vertical: 'IT',
    verdict: 'Берём',
    price: 4,
    link: 'https://github.com',
    note: 'Код и ревью. Здесь же лежит репозиторий MindSheet.',
  },
];
